# PostgreSQL Configuration
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TheaterBooking
    username: postgres
    password: root



  data:
    mongodb:
      uri: mongodb://localhost:27017/TheaterBooking

# Logging Configuration for MongoDB
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
